In [3]:
import pandas as pd

In [4]:
cf=pd.read_csv("OneDrive/Documents/Blinkit Project/customer_feedback.csv")

In [8]:
cust=pd.read_csv("OneDrive/Documents/Blinkit Project/customers.csv")

In [9]:
del_perf=pd.read_csv("OneDrive/Documents/Blinkit Project/delivery_performance.csv")

In [10]:
inv=pd.read_csv("OneDrive/Documents/Blinkit Project/inventory.csv")

In [11]:
mark_perf=pd.read_csv("OneDrive/Documents/Blinkit Project/marketing_performance.csv")

In [12]:
order_items=pd.read_csv("OneDrive/Documents/Blinkit Project/order_items.csv")

In [13]:
orders=pd.read_csv("OneDrive/Documents/Blinkit Project/orders.csv")

In [14]:
products=pd.read_csv("OneDrive/Documents/Blinkit Project/products.csv")

<font size= 6>**DATA CLEANING**</font>

In [54]:
cf

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
0,2234710,1961864118,30065862,4,"It was okay, nothing special.",Delivery,Neutral,2024-07-17
1,5450964,1549769649,9573071,3,The order was incorrect.,App Experience,Negative,2024-05-28
2,482108,9185164487,45477575,3,"It was okay, nothing special.",App Experience,Neutral,2024-09-23
3,4823104,9644738826,88067569,4,The product met my expectations.,App Experience,Neutral,2023-11-24
4,3537464,5427684290,83298567,3,Product was damaged during delivery.,Delivery,Negative,2023-11-20
...,...,...,...,...,...,...,...,...
4995,9024060,1669690997,62600289,3,Taste was not as expected.,Product Quality,Negative,2023-12-25
4996,4715968,8340761903,53640286,3,"Average experience, could improve.",Product Quality,Neutral,2023-11-27
4997,9621021,5936301790,87059497,4,"Average experience, could improve.",App Experience,Neutral,2024-06-21
4998,1134095,5710579377,67310893,4,"Average experience, could improve.",Delivery,Neutral,2024-06-06
4999,6578433,2494813730,28663279,4,"It was okay, nothing special.",Customer Service,Neutral,2023-08-23

In [6]:
cf.sort_values("feedback_id")

,feedback_id,order_id,customer_id,rating,feedback_text,feedback_category,sentiment,feedback_date
1451,947,8875605037,93867669,1,Customer service was not helpful.,App Experience,Negative,2023-09-27
324,5028,8830321199,93341057,5,Very fresh and well-packaged.,Product Quality,Positive,2024-08-10
2539,5348,935645101,63368244,3,Not worth the price I paid.,Product Quality,Negative,2023-09-27
2181,6201,9271384187,67749649,1,The packaging was poor.,Delivery,Negative,2023-11-28
4612,11042,1320638425,36833857,4,Good selection of products.,Customer Service,Positive,2023-04-26
...,...,...,...,...,...,...,...,...
3889,9992406,7485459856,89784343,4,"Nothing to complain about, but nothing excepti...",Delivery,Neutral,2023-09-15
1926,9992700,8310385249,97315135,1,Delivery was late and I was unhappy.,App Experience,Negative,2023-07-29
4726,9993994,1225289500,70529459,1,The packaging was poor.,App Experience,Negative,2024-03-31
4197,9997264,5953426781,79135318,4,"Delivery was fine, but the product could be be...",Delivery,Neutral,2023-12-10
3083,9999293,3770123374,29415527,4,"Delivery was fine, but the product could be be...",Product Quality,Neutral,2023-11-19

In [59]:
cf.dtypes

feedback_id                   int64
order_id                      int64
customer_id                   int64
rating                        int64
feedback_text                object
feedback_category            object
sentiment                    object
feedback_date        datetime64[ns]
dtype: object

In [56]:
cf.isnull().sum()

feedback_id          0
order_id             0
customer_id          0
rating               0
feedback_text        0
feedback_category    0
sentiment            0
feedback_date        0
dtype: int64

In [57]:
cf[cf.duplicated()]

Empty DataFrame
Columns: [feedback_id, order_id, customer_id, rating, feedback_text, feedback_category, sentiment, feedback_date]
Index: []

In [58]:
cf["feedback_date"]=pd.to_datetime(cf["feedback_date"],errors="")

In [60]:
cf.to_csv("OneDrive/Documents/Blinkit Project/customer_feedback.csv",index=False)

In [47]:
#=======================================
#customer_feedback table is cleaned 
#=======================================

In [48]:
cust

,customer_id,customer_name,email,phone,address,area,pincode,registration_date,customer_segment,total_orders,avg_order_value
0,97475543,Niharika Nagi,ektataneja@example.org,912987579691,"23, Nayar Path, Bihar Sharif-154625",Udupi,321865,2023-05-13,Premium,13,451.92
1,22077605,Megha Sachar,vedant45@example.com,915123179717,"51/302, Buch Chowk\nSrinagar-570271",Aligarh,149394,2024-06-18,Inactive,4,825.48
2,47822591,Hema Bahri,samiazaan@example.com,910034076149,"941\nAnne Street, Darbhanga 186125",Begusarai,621411,2024-09-25,Regular,17,1969.81
3,79726146,Zaitra Vig,ishanvi87@example.org,916264232390,"43/94, Ghosh, Alappuzha 635655",Kozhikode,826054,2023-10-04,New,4,220.09
4,57102800,Januja Verma,atideshpande@example.org,917293526596,"06\nOm, Ambarnath 477463",Ichalkaranji,730539,2024-03-22,Inactive,14,578.14
...,...,...,...,...,...,...,...,...,...,...,...
2495,48002829,Daksh Mandal,varkeymohammed@example.com,919587731286,"28/42, Venkataraman Ganj, Kishanganj-360157",Mumbai,45238,2024-01-25,Inactive,17,754.33
2496,57392064,Lavanya Jain,deshpandeom@example.com,916137420258,"391, Edwin Path, Korba 202726",Udupi,688100,2024-06-23,Regular,4,1540.81
2497,71688530,Umang Dash,gokhalenicholas@example.org,917595275963,"151, Parmer Ganj\nLoni 906431",Kavali,528749,2024-03-18,Regular,1,1541.22
2498,89051578,Zinal Natarajan,vyasfrado@example.com,911994009448,"H.No. 172, Khanna Street, Pudukkottai 610564",Alwar,586734,2024-09-06,Premium,12,1185.50
2499,78738569,Eiravati Sundaram,onkar24@example.com,914320353753,"H.No. 791, Sur Path\nBally 982559",Dewas,342448,2023-05-10,Inactive,4,376.50

In [53]:
cust.dtypes

customer_id            int64
customer_name         object
email                 object
phone                  int64
address               object
area                  object
pincode                int64
registration_date     object
customer_segment      object
total_orders           int64
avg_order_value      float64
dtype: object

In [59]:
cust.isnull().sum()

customer_id          0
customer_name        0
email                0
phone                0
address              0
area                 0
pincode              0
registration_date    0
customer_segment     0
total_orders         0
avg_order_value      0
dtype: int64

In [72]:
cust[cust.duplicated()]

Empty DataFrame
Columns: [customer_id, customer_name, email, phone, address, area, pincode, registration_date, customer_segment, total_orders, avg_order_value]
Index: []

In [73]:
#=======================================
#customers table is cleaned 
#=======================================

In [74]:
del_perf

,order_id,delivery_partner_id,promised_time,actual_time,delivery_time_minutes,distance_km,delivery_status,reasons_if_delayed
0,1961864118,63230,2024-07-17 08:52:01,2024-07-17 08:47:01,-5.0,0.96,On Time,NaN
1,1549769649,14983,2024-05-28 13:25:29,2024-05-28 13:27:29,2.0,0.98,On Time,Traffic
2,9185164487,39859,2024-09-23 13:25:12,2024-09-23 13:29:12,4.0,3.83,On Time,Traffic
3,9644738826,61497,2023-11-24 16:34:56,2023-11-24 16:33:56,-1.0,2.76,On Time,NaN
4,5427684290,84315,2023-11-20 05:17:39,2023-11-20 05:18:39,1.0,2.63,On Time,Traffic
...,...,...,...,...,...,...,...,...
4995,1669690997,90914,2023-12-25 16:05:20,2023-12-25 16:10:20,5.0,1.86,On Time,Traffic
4996,8340761903,27952,2023-11-27 09:38:43,2023-11-27 09:36:43,-2.0,3.31,On Time,NaN
4997,5936301790,9590,2024-06-21 19:23:09,2024-06-21 19:26:09,3.0,2.44,On Time,Traffic
4998,5710579377,29940,2024-06-06 15:12:13,2024-06-06 15:10:13,-2.0,1.76,On Time,NaN
4999,2494813730,32851,2023-08-23 12:20:18,2023-08-23 12:21:18,1.0,2.70,On Time,Traffic

In [75]:
del_perf.dtype

order_id                   int64
delivery_partner_id        int64
promised_time             object
actual_time               object
delivery_time_minutes    float64
distance_km              float64
delivery_status           object
reasons_if_delayed        object
dtype: object

In [76]:
del_perf.isnull().sum

order_id                    0
delivery_partner_id         0
promised_time               0
actual_time                 0
delivery_time_minutes       0
distance_km                 0
delivery_status             0
reasons_if_delayed       1902
dtype: int64

In [81]:
del_perf[del_perf.duplicated()]

Empty DataFrame
Columns: [order_id, delivery_partner_id, promised_time, actual_time, delivery_time_minutes, distance_km, delivery_status, reasons_if_delayed]
Index: []

In [82]:
#=======================================
#delivery performance table is cleaned 
#=======================================

In [21]:
inv

       product_id       date  stock_received  damaged_stock
0          153019 2023-03-17               4              2
1          848226 2023-03-17               4              2
2          965755 2023-03-17               1              0
3           39154 2023-03-17               4              0
4           34186 2023-03-17               3              2
...           ...        ...             ...            ...
75167      298985 2024-11-05               3              0
75168      679284 2024-11-05               3              0
75169      240179 2024-11-05               3              0
75170      673058 2024-11-05               3              2
75171      114414 2024-11-05               3              0

[75172 rows x 4 columns]

In [85]:
inv.isnull().sum()

product_id        0
date              0
stock_received    0
damaged_stock     0
dtype: int64

In [20]:
inv.dtypes

product_id                 int64
date              datetime64[ns]
stock_received             int64
damaged_stock              int64
dtype: object

In [19]:
inv["date"]=pd.to_datetime(inv["date"],errors="coerce",format="%Y-%m-%d")

In [24]:
inv[inv["product_id"].duplicated()]

       product_id       date  stock_received  damaged_stock
113        153019 2023-03-18               0              2
117         34186 2023-03-18               0              2
119        818990 2023-03-18               1              0
121        284460 2023-03-18               0              2
125        217710 2023-03-18               0              2
...           ...        ...             ...            ...
75167      298985 2024-11-05               3              0
75168      679284 2024-11-05               3              0
75169      240179 2024-11-05               3              0
75170      673058 2024-11-05               3              2
75171      114414 2024-11-05               3              0

[74904 rows x 4 columns]

In [23]:
inv.to_csv(r"C:\Users\prath\OneDrive\Documents\Blinkit Project\inventory.csv",index=False)

In [91]:
#=======================================
#inventory table is cleaned 
#=======================================

In [6]:
mark_perf

,campaign_id,campaign_name,date,target_audience,channel,impressions,clicks,conversions,spend,revenue_generated,roas
0,548299,New User Discount,2024-11-05,Premium,App,3130,163,78,1431.85,4777.75,3.60
1,390914,Weekend Special,2024-11-05,Inactive,App,3925,494,45,4506.34,6238.11,2.98
2,834385,Festival Offer,2024-11-05,Inactive,Email,7012,370,78,4524.23,2621.00,2.95
3,241523,Flash Sale,2024-11-05,Inactive,SMS,1115,579,86,3622.79,2955.00,2.84
4,595111,Membership Drive,2024-11-05,New Users,Email,7172,795,54,2888.99,8951.81,2.22
...,...,...,...,...,...,...,...,...,...,...,...
5395,381623,Membership Drive,2023-03-17,New Users,Email,8331,809,92,2363.07,3710.79,1.64
5396,493317,Category Promotion,2023-03-17,Premium,Social Media,5216,860,34,3922.53,7701.25,2.01
5397,879292,App Push Notification,2023-03-17,All,App,8480,734,20,1990.75,6650.41,3.98
5398,461129,Email Campaign,2023-03-17,New Users,Email,3569,568,10,4246.47,5880.42,2.50
5399,282514,Referral Program,2023-03-17,New Users,Social Media,5967,439,78,1511.93,8322.01,3.08

In [7]:
mark_perf.dtypes

campaign_id            int64
campaign_name         object
date                  object
target_audience       object
channel               object
impressions            int64
clicks                 int64
conversions            int64
spend                float64
revenue_generated    float64
roas                 float64
dtype: object

In [8]:
mark_perf.isnull().sum()

campaign_id          0
campaign_name        0
date                 0
target_audience      0
channel              0
impressions          0
clicks               0
conversions          0
spend                0
revenue_generated    0
roas                 0
dtype: int64

In [25]:
mark_perf[mark_perf["campaign_id"].duplicated()]

Empty DataFrame
Columns: [campaign_id, campaign_name, date, target_audience, channel, impressions, clicks, conversions, spend, revenue_generated, roas]
Index: []

In [ ]:
#=======================================
#marketing performance table is cleaned 
#=======================================

In [12]:
order_items

        order_id  product_id  quantity  unit_price
0     1961864118      642612         3      517.03
1     1549769649      378676         1      881.42
2     9185164487      741341         2      923.84
3     9644738826      561860         1      874.78
4     5427684290      602241         2      976.55
...          ...         ...       ...         ...
4995  1669690997      925482         3      475.04
4996  8340761903      124290         2       39.65
4997  5936301790      491314         3      973.44
4998  5710579377      319388         2      657.80
4999  2494813730      136533         1      826.21

[5000 rows x 4 columns]

In [13]:
order_items.isnull().sum()

order_id      0
product_id    0
quantity      0
unit_price    0
dtype: int64

In [14]:
order_items.dtypes

order_id        int64
product_id      int64
quantity        int64
unit_price    float64
dtype: object

In [16]:
order_items[order_items["order_id"].duplicated()]

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price]
Index: []

In [ ]:
#=======================================
#order items table is cleaned 
#=======================================

In [17]:
orders

,order_id,customer_id,order_date,promised_delivery_time,actual_delivery_time,delivery_status,order_total,payment_method,delivery_partner_id,store_id
0,1961864118,30065862,2024-07-17 08:34:01,2024-07-17 08:52:01,2024-07-17 08:47:01,On Time,3197.07,Cash,63230,4771
1,1549769649,9573071,2024-05-28 13:14:29,2024-05-28 13:25:29,2024-05-28 13:27:29,On Time,976.55,Cash,14983,7534
2,9185164487,45477575,2024-09-23 13:07:12,2024-09-23 13:25:12,2024-09-23 13:29:12,On Time,839.05,UPI,39859,9886
3,9644738826,88067569,2023-11-24 16:16:56,2023-11-24 16:34:56,2023-11-24 16:33:56,On Time,440.23,Card,61497,7917
4,5427684290,83298567,2023-11-20 05:00:39,2023-11-20 05:17:39,2023-11-20 05:18:39,On Time,2526.68,Cash,84315,2741
...,...,...,...,...,...,...,...,...,...,...
4995,1669690997,62600289,2023-12-25 15:46:20,2023-12-25 16:05:20,2023-12-25 16:10:20,On Time,1132.33,Cash,90914,1587
4996,8340761903,53640286,2023-11-27 09:18:43,2023-11-27 09:38:43,2023-11-27 09:36:43,On Time,2372.01,Cash,27952,3458
4997,5936301790,87059497,2024-06-21 19:09:09,2024-06-21 19:23:09,2024-06-21 19:26:09,On Time,3158.35,Cash,9590,7424
4998,5710579377,67310893,2024-06-06 14:58:13,2024-06-06 15:12:13,2024-06-06 15:10:13,On Time,1918.92,UPI,29940,6128
4999,2494813730,28663279,2023-08-23 12:04:18,2023-08-23 12:20:18,2023-08-23 12:21:18,On Time,1879.46,Card,32851,5588

In [19]:
orders.isnull().sum()

order_id                  0
customer_id               0
order_date                0
promised_delivery_time    0
actual_delivery_time      0
delivery_status           0
order_total               0
payment_method            0
delivery_partner_id       0
store_id                  0
dtype: int64

In [20]:
orders.dtypes

order_id                    int64
customer_id                 int64
order_date                 object
promised_delivery_time     object
actual_delivery_time       object
delivery_status            object
order_total               float64
payment_method             object
delivery_partner_id         int64
store_id                    int64
dtype: object

In [24]:
orders[orders["order_id"].duplicated()]

Empty DataFrame
Columns: [order_id, customer_id, order_date, promised_delivery_time, actual_delivery_time, delivery_status, order_total, payment_method, delivery_partner_id, store_id]
Index: []

In [ ]:
#=======================================
#order table is cleaned 
#=======================================

In [18]:
products

,product_id,product_name,category,brand,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
0,153019,Onions,Fruits & Vegetables,Aurora LLC,947.95,1263.93,25.0,3,13,88
1,11422,Potatoes,Fruits & Vegetables,Ramaswamy-Tata,127.16,169.55,25.0,3,20,65
2,669378,Potatoes,Fruits & Vegetables,Chadha and Sons,212.14,282.85,25.0,3,23,70
3,848226,Tomatoes,Fruits & Vegetables,Barad and Sons,209.59,279.45,25.0,3,10,51
4,890623,Onions,Fruits & Vegetables,"Sangha, Nagar and Varty",354.52,472.69,25.0,3,27,55
...,...,...,...,...,...,...,...,...,...,...
263,444361,Pain Reliever,Pharmacy,"Prakash, Bawa and Kale",822.63,1028.29,20.0,365,20,71
264,679284,Cough Syrup,Pharmacy,Pant LLC,877.89,1097.36,20.0,365,28,95
265,240179,Cough Syrup,Pharmacy,Ram-Suri,90.56,113.20,20.0,365,20,56
266,673058,Cough Syrup,Pharmacy,Balan-Madan,765.76,957.20,20.0,365,30,94
267,114414,Vitamins,Pharmacy,Kara-Golla,832.06,1040.07,20.0,365,26,66

In [27]:
products.describe()

,product_id,price,mrp,margin_percentage,shelf_life_days,min_stock_level,max_stock_level
count,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000,268.000000
mean,514855.940299,488.356828,680.434739,27.779851,231.757463,20.388060,74.753731
std,291391.529820,298.487200,419.772224,7.458753,151.205830,5.958546,14.591535
min,4452.000000,12.320000,17.600000,15.000000,3.000000,10.000000,50.000000
25%,273697.750000,226.717500,325.150000,20.000000,90.000000,15.000000,63.750000
50%,541459.000000,442.185000,616.970000,30.000000,365.000000,21.000000,73.000000
75%,754334.000000,779.445000,1056.620000,35.000000,365.000000,25.250000,88.000000
max,993331.000000,995.980000,1633.320000,40.000000,365.000000,30.000000,100.000000

In [37]:
products["category"].value_counts().sort_index()

category
Baby Care                16
Cold Drinks & Juices     22
Dairy & Breakfast        30
Fruits & Vegetables      27
Grocery & Staples        24
Household Care           27
Instant & Frozen Food    20
Personal Care            25
Pet Care                 25
Pharmacy                 25
Snacks & Munchies        27
Name: count, dtype: int64

In [39]:
products.isnull().sum()

product_id           0
product_name         0
category             0
brand                0
price                0
mrp                  0
margin_percentage    0
shelf_life_days      0
min_stock_level      0
max_stock_level      0
dtype: int64

In [40]:
products.dtypes

product_id             int64
product_name          object
category              object
brand                 object
price                float64
mrp                  float64
margin_percentage    float64
shelf_life_days        int64
min_stock_level        int64
max_stock_level        int64
dtype: object

In [41]:
products[products["product_id"].duplicated()]

Empty DataFrame
Columns: [product_id, product_name, category, brand, price, mrp, margin_percentage, shelf_life_days, min_stock_level, max_stock_level]
Index: []

In [42]:
#=======================================
#products table is cleaned 
#=======================================